### ISSUE TITLE
failed to use clichart. 

### ISSUE THREAD

**Issue by dracula51** [captsens/clichart#1]
Update: problem was caused by one uncompleted installation! I used the source to build and installed it by `easy_install clichart-0.5.9-py2.7.egg` in the `dist`, but got one problem although it showed clichart had been installed. 

Hi dear, 
I am not sure if what I did is correct. I installed the clichart and tried to start it, but got following error.
Can you please help to give some clue? Thanks a lot!
~/git/diameter/diameter-perf-test (master *)$ man clichart
No manual entry for clichart
See 'man 7 undocumented' for help when manual pages are not available.
~/git/diameter/diameter-perf-test (master *)$ clichart --help
Traceback (most recent call last):
  File "/usr/local/bin/clichart", line 9, in <module>
    load_entry_point('clichart==0.5.9', 'console_scripts', 'clichart')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
ImportError: No module named clichart.clichart

Best regards,
Lucas

**Comment by captsens** [comment]
Hi Lucas

What error did you see when you ran the install?

For your interest, clichart is getting pretty old now - I haven't done updated anything in 3 years, and it's more like 5 years since it saw active development.  It's no surprise that the installer doesn't work quite as well as it once did...

Cheers ........................... JD
